name: Build latest master and deploy

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.11.0
        with:
          java-version: 21
          java-distribution: liberica
          checkout-persist-credentials: true
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build with Maven
        run: mvn spring-boot:build-image -Pnative

      - name: Push Images to Docker Registry
        run: docker push -a bjoggis/linode4j
      - name: Create and push manifest
        run: |
          docker manifest create bjoggis/linode4j:${{ github.ref_name }} bjoggis/linode4j:${{ github.ref_name }}-x86_64
          docker manifest push bjoggis/linode4j:${{ github.ref_name }}
          docker manifest create bjoggis/linode4j:latest bjoggis/linode4j:${{ github.ref_name }}-x86_64
          docker manifest push bjoggis/linode4j:latest